# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0003_auto_20160117_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='summa',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='zakaz',
            field=models.CharField(default=1, max_length=255, verbose_name='Что заказал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='last_deal',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 20, 11, 1, 673983), verbose_name='Дата заказа'),
        ),
    ]
