# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 22:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0006_auto_20160118_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='last_deal',
        ),
        migrations.AddField(
            model_name='zakaz',
            name='list_deal',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 22, 51, 0, 296993), verbose_name='Дата заказа'),
        ),
    ]
