# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0007_auto_20160118_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakaz',
            old_name='zakaz',
            new_name='zakaz1',
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='list_deal',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 22, 56, 26, 954677), verbose_name='Дата заказа'),
        ),
    ]
