# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0009_auto_20160118_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='list_deal',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='summa',
        ),
    ]
