# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 23:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0010_auto_20160118_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='list_deal',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 23, 55, 58, 636965), verbose_name='Дата заказа'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='summa',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='zakaz1',
            field=models.CharField(default=datetime.datetime(2016, 1, 18, 23, 56, 18, 794118), max_length=255, verbose_name='Что заказал'),
            preserve_default=False,
        ),
    ]
