# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 23:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0011_auto_20160118_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='list_deal',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 18, 23, 56, 24, 621451), verbose_name='Дата заказа'),
        ),
    ]
