# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0012_auto_20160118_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='list_deal',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='summa',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='zakaz1',
        ),
    ]
