# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 01:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0013_auto_20160120_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='zakaz1',
            field=models.CharField(default=datetime.datetime(2016, 1, 20, 1, 17, 54, 960109), max_length=255, verbose_name='Что заказал'),
            preserve_default=False,
        ),
    ]
