# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0014_zakaz_zakaz1'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='list_deal',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 1, 19, 24, 697242), verbose_name='Дата заказа'),
        ),
    ]
