# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0015_zakaz_list_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='summa',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='list_deal',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 1, 21, 29, 816398), verbose_name='Дата заказа'),
        ),
    ]
