# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 04:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0016_auto_20160120_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='list_deal',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 20, 4, 19, 0, 886049), verbose_name='Дата заказа'),
        ),
    ]
