# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 04:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0017_auto_20160120_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='list_deal',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата заказа'),
        ),
    ]
